#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OTQxYmZkNDJkNDMwOGZiZGRkN2Y1YmUzMjZiYzRkMzhmNTllODE1ZjllOTFmZDRlMDRhZmYzMWM3MmExYjNlYzAwNzg4ZWVjZDg5YWVlMGQ1MzhkNDBmNWVlM2UyZWRiOTI4NQ==

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
